### ISSUE TITLE
Deprecate this project? (Maintenance / Security issuses)

### ISSUE THREAD

**Issue by dbrgn** [aquaspy/threemadeskaqua#12]
Hi, I found your package over the Snap store!

It seems that the Electron version used is very old and the package hasn't been maintained or updated since 2019. Right now "npm audit" reports 23 vulnerabilities, 6 of them with level "high". The electron version itself has multiple such advisories attached.

Since Threema now [provides an official electron wrapper](https://threema.ch/en/download#desktop), maybe it would be better to discontinue this project and take down the snap, in order not to expose users to security vulnerabilities?

**Comment by aquaspy** [comment]
Hi @dbrgn 

Yeah, that is correct.

I think I will just deprecate this one.

Thanks for the heads up and sorry for this.
